language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

branches:
  except:
    - gh-pages



install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer install


before_script:
  - sudo chmod 777 /etc/hosts
  - echo 127.0.0.1 mining > /etc/hosts
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - "mysql -e 'create database mpos;'"
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('mining') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - nohup php -S bone:8000 public/index.php &

script:
  - php vendor/bin/codecept build
  - php vendor/bin/codecept run unit --coverage --coverage-html --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
